export interface University {
  id: string
  name: string
  description: string
  location: string
  country: string
  established: number
  type: "public" | "private"
  ranking: number
  tuitionFee: string
  website: string
  email: string
  phone: string
  image: string
  programs: string[]
  facilities: string[]
  status: "active" | "inactive"
  addedAt: string
}

export const universities: University[] = [
  {
    id: "1",
    name: "Harvard University",
    description: "Harvard University is a private Ivy League research university in Cambridge, Massachusetts. Established in 1636, it is the oldest institution of higher learning in the United States.",
    location: "Cambridge, Massachusetts",
    country: "United States",
    established: 1636,
    type: "private",
    ranking: 1,
    tuitionFee: "$54,002 per year",
    website: "https://www.harvard.edu",
    email: "admissions@harvard.edu",
    phone: "+1 (617) 495-1000",
    image: "/universities/harvard.jpg",
    programs: ["Business Administration", "Law", "Medicine", "Engineering", "Computer Science"],
    facilities: ["Library", "Research Labs", "Sports Complex", "Student Housing", "Medical Center"],
    status: "active",
    addedAt: "2026-01-10",
  },
  {
    id: "2",
    name: "Stanford University",
    description: "Stanford University is a private research university in Stanford, California. Known for its entrepreneurship culture and proximity to Silicon Valley.",
    location: "Stanford, California",
    country: "United States",
    established: 1885,
    type: "private",
    ranking: 3,
    tuitionFee: "$56,169 per year",
    website: "https://www.stanford.edu",
    email: "admission@stanford.edu",
    phone: "+1 (650) 723-2300",
    image: "/universities/stanford.jpg",
    programs: ["Computer Science", "Engineering", "Business", "Medicine", "Law"],
    facilities: ["Innovation Lab", "Library", "Sports Stadium", "Research Centers", "Art Gallery"],
    status: "active",
    addedAt: "2026-01-12",
  },
  {
    id: "3",
    name: "University of Oxford",
    description: "The University of Oxford is a collegiate research university in Oxford, England. It is the oldest university in the English-speaking world.",
    location: "Oxford",
    country: "United Kingdom",
    established: 1096,
    type: "public",
    ranking: 2,
    tuitionFee: "£9,250 - £26,770 per year",
    website: "https://www.ox.ac.uk",
    email: "admissions@ox.ac.uk",
    phone: "+44 1865 270000",
    image: "/universities/oxford.jpg",
    programs: ["Philosophy", "Politics", "Economics", "Medicine", "Law"],
    facilities: ["Bodleian Library", "Museums", "Research Institutes", "Colleges", "Sports Facilities"],
    status: "active",
    addedAt: "2026-01-15",
  },
  {
    id: "4",
    name: "MIT",
    description: "Massachusetts Institute of Technology is a private research university in Cambridge, Massachusetts. Known for its strength in science, engineering, and technology.",
    location: "Cambridge, Massachusetts",
    country: "United States",
    established: 1861,
    type: "private",
    ranking: 5,
    tuitionFee: "$55,510 per year",
    website: "https://www.mit.edu",
    email: "admissions@mit.edu",
    phone: "+1 (617) 253-1000",
    image: "/universities/mit.jpg",
    programs: ["Computer Science", "Artificial Intelligence", "Engineering", "Physics", "Mathematics"],
    facilities: ["Media Lab", "Research Centers", "Libraries", "Sports Complex", "Innovation Hub"],
    status: "active",
    addedAt: "2026-01-18",
  },
  {
    id: "5",
    name: "University of Cambridge",
    description: "The University of Cambridge is a collegiate research university in Cambridge, England. Founded in 1209, it is the second-oldest university in the English-speaking world.",
    location: "Cambridge",
    country: "United Kingdom",
    established: 1209,
    type: "public",
    ranking: 4,
    tuitionFee: "£9,250 - £33,825 per year",
    website: "https://www.cam.ac.uk",
    email: "admissions@cam.ac.uk",
    phone: "+44 1223 337733",
    image: "/universities/cambridge.jpg",
    programs: ["Mathematics", "Natural Sciences", "Engineering", "Medicine", "Computer Science"],
    facilities: ["University Library", "Museums", "Colleges", "Laboratories", "Sports Grounds"],
    status: "active",
    addedAt: "2026-01-20",
  },
  {
    id: "6",
    name: "ETH Zurich",
    description: "ETH Zurich is a public research university in Zurich, Switzerland. It is one of the leading universities for technology and natural sciences worldwide.",
    location: "Zurich",
    country: "Switzerland",
    established: 1855,
    type: "public",
    ranking: 7,
    tuitionFee: "CHF 1,460 per year",
    website: "https://ethz.ch",
    email: "admissions@ethz.ch",
    phone: "+41 44 632 11 11",
    image: "/universities/eth.jpg",
    programs: ["Engineering", "Computer Science", "Physics", "Mathematics", "Architecture"],
    facilities: ["Research Labs", "Libraries", "Data Centers", "Sports Facilities", "Innovation Park"],
    status: "active",
    addedAt: "2026-01-25",
  },
  {
    id: "7",
    name: "National University of Singapore",
    description: "NUS is Singapore's flagship university offering a global approach to education and research with a focus on Asian perspectives.",
    location: "Singapore",
    country: "Singapore",
    established: 1905,
    type: "public",
    ranking: 11,
    tuitionFee: "$17,550 - $58,450 per year",
    website: "https://www.nus.edu.sg",
    email: "admissions@nus.edu.sg",
    phone: "+65 6516 6666",
    image: "/universities/nus.jpg",
    programs: ["Business", "Computer Science", "Engineering", "Medicine", "Law"],
    facilities: ["Libraries", "Innovation Labs", "Medical Centers", "Sports Complex", "Research Institutes"],
    status: "active",
    addedAt: "2026-02-01",
  },
  {
    id: "8",
    name: "University of Toronto",
    description: "The University of Toronto is a public research university in Toronto, Ontario, Canada. It is one of the world's top research-intensive universities.",
    location: "Toronto, Ontario",
    country: "Canada",
    established: 1827,
    type: "public",
    ranking: 18,
    tuitionFee: "CAD $6,100 - $58,160 per year",
    website: "https://www.utoronto.ca",
    email: "admissions@utoronto.ca",
    phone: "+1 (416) 978-2011",
    image: "/universities/toronto.jpg",
    programs: ["Medicine", "Engineering", "Computer Science", "Business", "Arts & Science"],
    facilities: ["Libraries", "Research Centers", "Medical Facilities", "Athletic Centers", "Museums"],
    status: "active",
    addedAt: "2026-02-05",
  },
]
